export const CONTRACT_ID = "dev-1668479767552-98598205727871";

export const JOBS_CATEGORIES = [
  "web | html | info design",
  "business | mgmt",
  "marketing | advertising | pr",
  "et cetera",
  "writing | editing",
  "software | qa | dba | etc",
  "accounting | finance",
  "admin | office",
  "art | media | design",
  "healthcare",
  "retail | wholesale",
  "nonprofit",
  "legal | paralegal",
  "architect | engineer | cad",
  "sales",
  "systems | networking",
  "tv | film | video | radio",
  "human resource",
  "technical support",
  "education | teaching",
  "skilled trades | artisan",
  "government",
  "science | biotech",
  "customer service",
  "transportation",
  "salon | spa | fitness",
  "real estate",
  "manufacturing",
  "food | beverage | hospitality",
  "general labor",
  "security",
];

export const HOUSING_CATEGORIES = [
  "apartments | housing for rent",
  "wanted: apts",
  "rooms & shares",
  "wanted: room | share",
  "sublets & temporary",
  "office & commercial",
  "parking & storage",
  "wanted: sublet | temp",
  "housing swap",
  "vacation rentals",
  "wanted: real estate",
  "real estate - by owner",
];

export const COMMUNITY_CATEGORIES = [
  "general",
  "volunteers",
  "activity partners",
  "rideshare",
  "pets",
  "childcare",
  "missed connections",
  "artists",
  "musicians",
  "politics",
  "lost & found",
  "rants & raves",
  "groups",
  "local news and views",
];

export const FOR_SALE_CATEGORIES = [
  "general for sale",
  "computers",
  "wanted",
  "barter",
  "tickets",
  "bicycles",
  "motorcycles | scooters",
  "garage & moving sales",
  "books & magazines",
  "sporting goods",
  "clothing & accessories",
  "collectibles",
  "electronics",
  "household items",
  "musical instruments",
  "free stuff",
  "baby & kid stuff",
  "cds | dvds | vhs",
  "tools",
  "boats",
  "jewelry",
  "auto parts",
  "rvs",
  "toys & games",
  "farm & garden",
  "business | commercial",
  "arts & crafts",
  "materials",
  "photo | video",
  "furniture",
  "cars & trucks",
  "appliances",
  "antiques",
  "video gaming",
  "health and beauty",
  "cell phones",
  "atvs | utvs | snowmobiles",
  "heavy equipment",
  "motorcycle parts",
  "bicycle parts",
  "computer parts",
  "boat parts",
  "auto wheels & tires",
  "trailers",
  "aviation",
];
